name: build

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y neofetch duf

      - name: Show host info
        run: |
          echo -e "\033[32mSystem info:\033[0m"
          neofetch --off --color_blocks off --stdout

          echo -e "\033[32mCPU info:\033[0m"
          lscpu

          echo -e "\033[32mMemory info:\033[0m"
          free -h

          echo -e "\033[32mDisk space info:\033[0m"
          df -hT ${PWD}
          duf

      - name: Show remaining space
        run: |
          echo -e "\033[32mDisk space info:\033[0m"
          df -hT ${PWD}
          duf

