name: free-disk-space

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

    - name: Free disk space
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h

      - name: Install required packages
        run: |
          sudo apt update
          sudo apt install -y neofetch duf

      - name: Show host info
        run: |
          lscpu
          free -h
          df -hT ${PWD}
          neofetch

      - name: Show remaining space
        run: |
          duf

